name: SaltRiverCyclists
favicon: null
layout_spectrum: 0.6174738057889044
typography_spectrum: 0.9830975795630366
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d4ab8'
    - '#0f1d3e'
    - '#6986cf'
    - '#a0b2e0'
  brandStrength: 0.23533180844970047
  lightness: 0.2955633387900889
  saturation: 0.8836382273584604
  rhythmicContrast: 0.7717068961355835
purpose: []
